### ISSUE TITLE
Bug: QuorumCallError does not work with errors.Is and errors.As

### ISSUE THREAD

**Issue by meling** [relab/gorums#195]
This does not work as expected because `QuorumCallError` does not implement the `Is` and `As` methods.
```go
// Assume err is a gorums.QuorumCallError
if errors.Is(err, context.DeadlineExceeded) {
	// handle deadline exceeded
}
```
This needs to be fixed in `QuorumCallError` and possibly in `quorumcall.go`:
```go
func (c RawConfiguration) QuorumCall(ctx context.Context, d QuorumCallData) (resp protoreflect.ProtoMessage, err error) {
```
And similar uses of the `QuorumCallError` in other call types.

We should use the standard Go context and error handling pattern.

Tasks:
- [ ] Implement tests for QuorumCallError with deadlines
- [ ] Implement fix for the `Is` and `As` methods.
- [ ] Document the pattern to check for things like `context.DeadlineExceeded` etc.

**Comment by meling** [comment]
Documents to review:
- [context](https://pkg.go.dev/context) package
- [errors](https://pkg.go.dev/errors) package
- Blog: [Go Concurrency Patterns: Context](https://go.dev/blog/context)
- Blog: [Contexts and structs](https://go.dev/blog/context-and-structs)
- Blog: [Working with Errors in Go 1.13](https://go.dev/blog/go1.13-errors)

**Comment by meling** [comment]
This is partially implemented; we can use the `errors.Is` now, but not sure about `errors.As`...
